export default {
  login: "praveen-1995",
  id: 44305655,
  node_id: "MDQ6VXNlcjQ0MzA1NjU1",
  avatar_url: "https://avatars.githubusercontent.com/u/44305655?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/praveen-1995",
  html_url: "https://github.com/praveen-1995",
  followers_url: "https://api.github.com/users/praveen-1995/followers",
  following_url:
    "https://api.github.com/users/praveen-1995/following{/other_user}",
  gists_url: "https://api.github.com/users/praveen-1995/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/praveen-1995/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/praveen-1995/subscriptions",
  organizations_url: "https://api.github.com/users/praveen-1995/orgs",
  repos_url: "https://api.github.com/users/praveen-1995/repos",
  events_url: "https://api.github.com/users/praveen-1995/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/praveen-1995/received_events",
  type: "User",
  site_admin: false,
  name: "Praveen Kumar",
  company: "Coding",
  blog: "github.com/praveen-1995",
  location: "United States",
  email: null,
  hireable: null,
  bio: "I am learning to code and create simple projects.",
  twitter_username: "Praveen60606542",
  public_repos: 46,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: "2018-10-19T21:29:59Z",
  updated_at: "2022-09-09T05:28:25Z",
};
